// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmvxieavvyojdqcuxoog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdnhpZWF2dnlvamRxY3V4b29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzODM0MTEsImV4cCI6MjA1MDk1OTQxMX0.R-wA2FrEaFnaXoQXyuG-FSOr62lMzyS1IYsoKUqJAAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);